package neu.edu;
// Generated Dec 13, 2016 8:59:55 PM by Hibernate Tools 5.1.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Comments generated by hbm2java
 */
public class Comments implements java.io.Serializable {

	private Integer commentId;
	private Reviews reviews;
	private User user;
	private String commentDesc;
	private Set<Replies> replieses = new HashSet<Replies>(0);

	public Comments() {
	}

	public Comments(Reviews reviews, User user, String commentDesc, Set<Replies> replieses) {
		this.reviews = reviews;
		this.user = user;
		this.commentDesc = commentDesc;
		this.replieses = replieses;
	}

	public Integer getCommentId() {
		return this.commentId;
	}

	public void setCommentId(Integer commentId) {
		this.commentId = commentId;
	}

	public Reviews getReviews() {
		return this.reviews;
	}

	public void setReviews(Reviews reviews) {
		this.reviews = reviews;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getCommentDesc() {
		return this.commentDesc;
	}

	public void setCommentDesc(String commentDesc) {
		this.commentDesc = commentDesc;
	}

	public Set<Replies> getReplieses() {
		return this.replieses;
	}

	public void setReplieses(Set<Replies> replieses) {
		this.replieses = replieses;
	}

}
