package neu.edu;
// Generated Dec 13, 2016 8:59:55 PM by Hibernate Tools 5.1.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer implements java.io.Serializable {

	private int customerId;
	private User user;
	private String contactNo;
	private String status;
	private Set<Reviews> reviewses = new HashSet<Reviews>(0);

	public Customer() {
	}

	public Customer(User user) {
		this.user = user;
	}

	public Customer(User user, String contactNo, String status, Set<Reviews> reviewses) {
		this.user = user;
		this.contactNo = contactNo;
		this.status = status;
		this.reviewses = reviewses;
	}

	public int getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(int customerId) {
		this.customerId = customerId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getContactNo() {
		return this.contactNo;
	}

	public void setContactNo(String contactNo) {
		this.contactNo = contactNo;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Set<Reviews> getReviewses() {
		return this.reviewses;
	}

	public void setReviewses(Set<Reviews> reviewses) {
		this.reviewses = reviewses;
	}

}
