package neu.edu;
// Generated Dec 13, 2016 8:59:55 PM by Hibernate Tools 5.1.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Owner generated by hbm2java
 */
public class Owner implements java.io.Serializable {

	private int ownerId;
	private User user;
	private String contactNo;
	private Set<Restaurant> restaurants = new HashSet<Restaurant>(0);

	public Owner() {
	}

	public Owner(User user) {
		this.user = user;
	}

	public Owner(User user, String contactNo, Set<Restaurant> restaurants) {
		this.user = user;
		this.contactNo = contactNo;
		this.restaurants = restaurants;
	}

	public int getOwnerId() {
		return this.ownerId;
	}

	public void setOwnerId(int ownerId) {
		this.ownerId = ownerId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getContactNo() {
		return this.contactNo;
	}

	public void setContactNo(String contactNo) {
		this.contactNo = contactNo;
	}

	public Set<Restaurant> getRestaurants() {
		return this.restaurants;
	}

	public void setRestaurants(Set<Restaurant> restaurants) {
		this.restaurants = restaurants;
	}

}
