package neu.edu;
// Generated Dec 13, 2016 8:59:55 PM by Hibernate Tools 5.1.0.CR1

/**
 * Replies generated by hbm2java
 */
public class Replies implements java.io.Serializable {

	private int replyId;
	private Comments comments;
	private User user;
	private String replyDesc;

	public Replies() {
	}

	public Replies(int replyId) {
		this.replyId = replyId;
	}

	public Replies(int replyId, Comments comments, User user, String replyDesc) {
		this.replyId = replyId;
		this.comments = comments;
		this.user = user;
		this.replyDesc = replyDesc;
	}

	public int getReplyId() {
		return this.replyId;
	}

	public void setReplyId(int replyId) {
		this.replyId = replyId;
	}

	public Comments getComments() {
		return this.comments;
	}

	public void setComments(Comments comments) {
		this.comments = comments;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getReplyDesc() {
		return this.replyDesc;
	}

	public void setReplyDesc(String replyDesc) {
		this.replyDesc = replyDesc;
	}

}
