package neu.edu;
// Generated Dec 13, 2016 8:59:55 PM by Hibernate Tools 5.1.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Restaurant generated by hbm2java
 */
public class Restaurant implements java.io.Serializable {

	private Integer restaurantId;
	private Owner owner;
	private User user;
	private String restaurantName;
	private String location;
	private Integer starRating;
	private String type;
	private String approvalStatus;
	private Set<Reviews> reviewses = new HashSet<Reviews>(0);

	public Restaurant() {
	}

	public Restaurant(Owner owner, User user, String restaurantName, String location, Integer starRating, String type,
			String approvalStatus, Set<Reviews> reviewses) {
		this.owner = owner;
		this.user = user;
		this.restaurantName = restaurantName;
		this.location = location;
		this.starRating = starRating;
		this.type = type;
		this.approvalStatus = approvalStatus;
		this.reviewses = reviewses;
	}

	public Integer getRestaurantId() {
		return this.restaurantId;
	}

	public void setRestaurantId(Integer restaurantId) {
		this.restaurantId = restaurantId;
	}

	public Owner getOwner() {
		return this.owner;
	}

	public void setOwner(Owner owner) {
		this.owner = owner;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getRestaurantName() {
		return this.restaurantName;
	}

	public void setRestaurantName(String restaurantName) {
		this.restaurantName = restaurantName;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public Integer getStarRating() {
		return this.starRating;
	}

	public void setStarRating(Integer starRating) {
		this.starRating = starRating;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getApprovalStatus() {
		return this.approvalStatus;
	}

	public void setApprovalStatus(String approvalStatus) {
		this.approvalStatus = approvalStatus;
	}

	public Set<Reviews> getReviewses() {
		return this.reviewses;
	}

	public void setReviewses(Set<Reviews> reviewses) {
		this.reviewses = reviewses;
	}

}
