package neu.edu;
// Generated Dec 13, 2016 8:59:55 PM by Hibernate Tools 5.1.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Reviews generated by hbm2java
 */
public class Reviews implements java.io.Serializable {

	private Integer reviewId;
	private Customer customer;
	private Restaurant restaurant;
	private Integer starRating;
	private String comments;
	private Integer serviceRating;
	private Integer foodRating;
	private Integer cost;
	private Set<Comments> commentses = new HashSet<Comments>(0);

	public Reviews() {
	}

	public Reviews(Customer customer, Restaurant restaurant, Integer starRating, String comments, Integer serviceRating,
			Integer foodRating, Integer cost, Set<Comments> commentses) {
		this.customer = customer;
		this.restaurant = restaurant;
		this.starRating = starRating;
		this.comments = comments;
		this.serviceRating = serviceRating;
		this.foodRating = foodRating;
		this.cost = cost;
		this.commentses = commentses;
	}

	public Integer getReviewId() {
		return this.reviewId;
	}

	public void setReviewId(Integer reviewId) {
		this.reviewId = reviewId;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public Restaurant getRestaurant() {
		return this.restaurant;
	}

	public void setRestaurant(Restaurant restaurant) {
		this.restaurant = restaurant;
	}

	public Integer getStarRating() {
		return this.starRating;
	}

	public void setStarRating(Integer starRating) {
		this.starRating = starRating;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public Integer getServiceRating() {
		return this.serviceRating;
	}

	public void setServiceRating(Integer serviceRating) {
		this.serviceRating = serviceRating;
	}

	public Integer getFoodRating() {
		return this.foodRating;
	}

	public void setFoodRating(Integer foodRating) {
		this.foodRating = foodRating;
	}

	public Integer getCost() {
		return this.cost;
	}

	public void setCost(Integer cost) {
		this.cost = cost;
	}

	public Set<Comments> getCommentses() {
		return this.commentses;
	}

	public void setCommentses(Set<Comments> commentses) {
		this.commentses = commentses;
	}

}
