package neu.edu;
// Generated Nov 11, 2016 10:46:41 PM by Hibernate Tools 5.1.0.CR1

/**
 * ResumeDetails generated by hbm2java
 */
public class ResumeDetails implements java.io.Serializable {

	private String username;
	private String password;
	private String name;
	private String dob;
	private String gender;
	private String about;
	private String education;
	private String gpa;
	private String location;
	private String project1;
	private String projectdesc1;
	private String project2;
	private String projectdesc2;
	private String project3;
	private String projectdesc3;
	private String reference;
	private String skill1;
	private String rating1;
	private String skill2;
	private String rating2;
	private String skill3;
	private String rating3;
	private Integer flag;

	public ResumeDetails() {
	}

	public ResumeDetails(String username) {
		this.username = username;
	}

	public ResumeDetails(String username, String password, String name, String dob, String gender, String about,
			String education, String gpa, String location, String project1, String projectdesc1, String project2,
			String projectdesc2, String project3, String projectdesc3, String reference, String skill1, String rating1,
			String skill2, String rating2, String skill3, String rating3, Integer flag) {
		this.username = username;
		this.password = password;
		this.name = name;
		this.dob = dob;
		this.gender = gender;
		this.about = about;
		this.education = education;
		this.gpa = gpa;
		this.location = location;
		this.project1 = project1;
		this.projectdesc1 = projectdesc1;
		this.project2 = project2;
		this.projectdesc2 = projectdesc2;
		this.project3 = project3;
		this.projectdesc3 = projectdesc3;
		this.reference = reference;
		this.skill1 = skill1;
		this.rating1 = rating1;
		this.skill2 = skill2;
		this.rating2 = rating2;
		this.skill3 = skill3;
		this.rating3 = rating3;
		this.flag = flag;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDob() {
		return this.dob;
	}

	public void setDob(String dob) {
		this.dob = dob;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getAbout() {
		return this.about;
	}

	public void setAbout(String about) {
		this.about = about;
	}

	public String getEducation() {
		return this.education;
	}

	public void setEducation(String education) {
		this.education = education;
	}

	public String getGpa() {
		return this.gpa;
	}

	public void setGpa(String gpa) {
		this.gpa = gpa;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public String getProject1() {
		return this.project1;
	}

	public void setProject1(String project1) {
		this.project1 = project1;
	}

	public String getProjectdesc1() {
		return this.projectdesc1;
	}

	public void setProjectdesc1(String projectdesc1) {
		this.projectdesc1 = projectdesc1;
	}

	public String getProject2() {
		return this.project2;
	}

	public void setProject2(String project2) {
		this.project2 = project2;
	}

	public String getProjectdesc2() {
		return this.projectdesc2;
	}

	public void setProjectdesc2(String projectdesc2) {
		this.projectdesc2 = projectdesc2;
	}

	public String getProject3() {
		return this.project3;
	}

	public void setProject3(String project3) {
		this.project3 = project3;
	}

	public String getProjectdesc3() {
		return this.projectdesc3;
	}

	public void setProjectdesc3(String projectdesc3) {
		this.projectdesc3 = projectdesc3;
	}

	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

	public String getSkill1() {
		return this.skill1;
	}

	public void setSkill1(String skill1) {
		this.skill1 = skill1;
	}

	public String getRating1() {
		return this.rating1;
	}

	public void setRating1(String rating1) {
		this.rating1 = rating1;
	}

	public String getSkill2() {
		return this.skill2;
	}

	public void setSkill2(String skill2) {
		this.skill2 = skill2;
	}

	public String getRating2() {
		return this.rating2;
	}

	public void setRating2(String rating2) {
		this.rating2 = rating2;
	}

	public String getSkill3() {
		return this.skill3;
	}

	public void setSkill3(String skill3) {
		this.skill3 = skill3;
	}

	public String getRating3() {
		return this.rating3;
	}

	public void setRating3(String rating3) {
		this.rating3 = rating3;
	}

	public Integer getFlag() {
		return this.flag;
	}

	public void setFlag(Integer flag) {
		this.flag = flag;
	}

}
